# Site settings
baseURL = "https://stanislav-portfolio.netlify.app/"
languageCode = "en-us"
title = "Stanislav's Portfolio"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Stanislav Makarov"
  description = "Aspiring Finance Professional"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "SM99"
    subtitle = ""
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "My CV"
      url = "post/CV_Stanislav_Makarov.pdf"

    #[[params.navigation.links]]
    #  name = "Generic Blog"
    #  url = "blogs/ipsum"

    #[[params.navigation.links]]
    #  name = "Elements"
    #  url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "My Projects"
      url = "projects"

    # Button Style 2
    #[[params.navigation.button2]]
    #  name = "Log In"
    #  url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hello, my name is Stanislav"
    subtitle = "I am an aspiring finance professional with interest in data analytics"
    buttonText = "My Projects"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "My First Steps with ggplot2"
      subtitle = "Alcohol Consumption"
      image = "Alcohol.jpg"
      url = "projects/homework1"

    [[params.tiles.showcase]]
      title = "Covid Statistics"
      subtitle = "by comorbidities and ICU admission"
      image = "covid.jpg"
      url = "projects/homework2"

    [[params.tiles.showcase]]
      title = "My Experience"
      subtitle = "1-page CV"
      image = "yield.jpg"
      url = "projects/yield_inversion"

    [[params.tiles.showcase]]
      title = "Hong Kong Airbnb Analysis"
      subtitle = "In search for best linear model"
      image = "HK.jpg"
      url = "projects/Hong_Kong"

    #[[params.tiles.showcase]]
    #  title = "Consequat"
    #  subtitle = "Ipsum Dolor Sit Amet"
    #  image = "pic05.jpg"
    #  url = "blogs/ipsum"

    #[[params.tiles.showcase]]
    #  title = "Etiam"
    #  subtitle = "Feugiat Amet Tempus"
    #  image = "pic06.jpg"
    #  url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About Me"
    subtitle = "I am a current Masters in Financial Analysis student at London Business School.
    "Before coming to the London Business School I graduated from a dual degree programme of Higher School of Economics and University of London in Economics major
    "During the undergraduate I gradually developed interest in the Corporate Finance sphere and now I am looking for opportunities to start my career as an Investment Banker in London.
    "Still I am willing to explore broader spectrum of subject and one of the spheres I am interested in is Data Analytics.""
    buttonText = "1-page CV"
    url = "post/CV_Stanislav_Makarov.pdf"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"
    formEmail = "smakarov.mfa2021@london.edu"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "smakarov.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Mobile Phone"
    phone = "07818 280395"

    [[params.contact.address]]
    title = "Address"
    street = "Regent's Park"
    city = "London, NW1 4SA"
    country = "United Kingdom"
    

  # Footer section
  [params.footer]
    enable = true
    copyright = "Stanislav Makarov"

    # Uses font awesome icons
    #[[params.footer.social]]
    #  icon = "fa-twitter"
    #  url= "https://www.twitter.com"
    #  label = "Twitter"

    #[[params.footer.social]]
    #  icon = "fa-facebook"
    #  url= "https://www.facebook.com"
    #  label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/makstaa/"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/s-makarov"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/stanislav-makarov/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
